fix: argument collision --config changed to --config-file
hms-networks/kolibri-cli pull request #8
Opened 2022-01-05 10:54 UTC by arbue

fixes the collision of the --config argument for setting the custom config file path and the --config parameter in the permission.node.set RPC.

2022-01-10 15:02 UTC, anelhms requested changes

2022-01-10 15:02 UTC, anelhms commented on src/index.ts
> +        createDefaultConfigFileIfNotExists(defaultConfigFile);
A non default path will not be created as it is now. I think this should be below the line  const configFile = await parseConfigFileArg() ?? defaultConfigFile;
And maybe name createConfigFileIfNotExists.

const configFile = await parseConfigFileArg() ?? defaultConfigFile;
createConfigFileIfNotExists(configFile)

2022-01-10 15:15 UTC, arbue commented on src/index.ts
> +    const argv = await yargsInstance.argv;
Same as above.

2022-01-10 15:15 UTC, arbue commented on src/index.ts
> +    const yargsInstance = yargs(hideBin(process.argv))
Same as above.

2022-01-10 15:15 UTC, arbue commented on src/index.ts
> +    const configFileArg = 'config-file';
On direct assignments the type is inferred automatically. So the compiler knows the correct type. In that case its string.

2022-01-11 08:00 UTC, anelhms commented on src/index.ts
> +        createDefaultConfigFileIfNotExists(defaultConfigFile);
aah yes, nvm then

2022-01-11 08:00 UTC, anelhms approved these changes

2022-01-11 08:07 UTC, dahahms approved these changes

2022-01-11 11:42 UTC, merged